spring:
  ai:
    openai:
      api-key: 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
      base-url: https://api.groq.com/openai

ai:
  models:
    nutrition:
      model: llama-3.1-8b-instant
      temperature: 0.3
    workout:
      model: llama-3.1-8b-instant
      temperature: 0.7